-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at <a href="https://github.com/pgadmin-org/pgadmin4/issues/new/choose" class="_blanktarget">https://github.com/pgadmin-org/pgadmin4/issues/new/choose</a> if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.book
(
    id integer NOT NULL,
    isbn character varying(100) NOT NULL,
    titre character varying(100) NOT NULL,
    description character varying(512),
    PRIMARY KEY (id),
    UNIQUE (isbn)
);

CREATE TABLE IF NOT EXISTS public.author
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    firstname character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.author_book
(
    idauthor integer,
    idbook integer,
    PRIMARY KEY (idauthor, idbook)
);

ALTER TABLE IF EXISTS public.author_book
    ADD FOREIGN KEY (idauthor)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_book
    ADD FOREIGN KEY (idbook)
    REFERENCES public.book (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

INSERT INTO public.book
(id, isbn, titre, description)
VALUES(1, '12345678', 'Harry Potter 1', 'Le magicien');

END;
